# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindowUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(632, 425)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../UI/Resources/box-zipper.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lbl_Instructions = QtWidgets.QLabel(self.centralwidget)
        self.lbl_Instructions.setGeometry(QtCore.QRect(20, 10, 321, 16))
        self.lbl_Instructions.setObjectName("lbl_Instructions")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(20, 30, 591, 311))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setLineWidth(2)
        self.frame.setObjectName("frame")
        self.treeWidget = QtWidgets.QTreeWidget(self.frame)
        self.treeWidget.setGeometry(QtCore.QRect(10, 10, 571, 291))
        self.treeWidget.setAcceptDrops(False)
        self.treeWidget.setFrameShadow(QtWidgets.QFrame.Plain)
        self.treeWidget.setTabKeyNavigation(True)
        self.treeWidget.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.treeWidget.setAnimated(False)
        self.treeWidget.setAllColumnsShowFocus(False)
        self.treeWidget.setObjectName("treeWidget")
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        self.treeWidget.header().setDefaultSectionSize(150)
        self.treeWidget.header().setHighlightSections(True)
        self.treeWidget.header().setMinimumSectionSize(125)
        self.btn_Extract = QtWidgets.QPushButton(self.centralwidget)
        self.btn_Extract.setGeometry(QtCore.QRect(520, 340, 93, 31))
        self.btn_Extract.setObjectName("btn_Extract")
        self.btn_Clear = QtWidgets.QPushButton(self.centralwidget)
        self.btn_Clear.setGeometry(QtCore.QRect(420, 340, 93, 31))
        self.btn_Clear.setObjectName("btn_Clear")
        self.btn_Settings = QtWidgets.QPushButton(self.centralwidget)
        self.btn_Settings.setGeometry(QtCore.QRect(20, 340, 93, 31))
        self.btn_Settings.setObjectName("btn_Settings")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 632, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ExtractPy"))
        self.lbl_Instructions.setText(_translate("MainWindow", "Drag and drop files or folders below to extract them:"))
        self.treeWidget.setSortingEnabled(True)
        self.treeWidget.headerItem().setText(0, _translate("MainWindow", "Files"))
        self.treeWidget.headerItem().setText(1, _translate("MainWindow", "Status"))
        self.treeWidget.headerItem().setText(2, _translate("MainWindow", "Progress"))
        __sortingEnabled = self.treeWidget.isSortingEnabled()
        self.treeWidget.setSortingEnabled(False)
        self.treeWidget.topLevelItem(0).setText(0, _translate("MainWindow", "en_windows_7_professional"))
        self.treeWidget.topLevelItem(1).setText(0, _translate("MainWindow", "en_office_2007_home"))
        self.treeWidget.setSortingEnabled(__sortingEnabled)
        self.btn_Extract.setText(_translate("MainWindow", "Extract"))
        self.btn_Clear.setText(_translate("MainWindow", "Clear"))
        self.btn_Settings.setText(_translate("MainWindow", "Settings"))
